### ISSUE TITLE
Sync Resource Packs through Git

### ISSUE THREAD

**Issue by FOREVEREALIZE** [NewWind-Modpacks/Waste-of-World#12]
Generated from task in #3

**Comment by FOREVEREALIZE** [comment]
@Kevadroz which resource packs need to be synced?

**Comment by Kevadroz** [comment]
I'll see later today, normally the ones that are always used are in the paxi folder (which is already in the repo, if you didn't notice the texture changes in yesterday's testing) and the ones in the resourcepacks folder are whatever we are looking for including or any custom ones we are working on.

**Comment by FOREVEREALIZE** [comment]
Okay, I'll assign you for now.

**Comment by Kevadroz** [comment]
Forgot to close this, oops.
