### ISSUE TITLE
Falta la libreria PuzzlesLib

### ISSUE THREAD

**Issue by FOREVEREALIZE** [NewWind-Modpacks/Waste-of-World#2]
Al abrir el Modpack (version bda832a), el juego lanza una `RuntimeException` con `NoClassDefFoundError`. Al analizar los logs, he instalado la ultima version de [Puzzles Lib](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib) y el juego ha abierto correctamente.

**Comment by Kevadroz** [comment]
Cual es la cantidad de mods cargados? con puzzlesLib
