### ISSUE TITLE
Pressing number keys 6, 7, 8 or 9 causes the TinyInv Hotbar to bug

### ISSUE THREAD

**Issue by FOREVEREALIZE** [NewWind-Modpacks/Waste-of-World#4]
While using TinyInv, pressing <kbd>6</kbd>, <kbd>7</kbd>, <kbd>8</kbd> or <kbd>9</kbd> on the keyboard causes the TinyInv Hotbar to bug out and highlight a non-existent slot.

![2023-11-25_20 36 02](https://github.com/NewWind-Modpacks/Waste-of-World/assets/60579848/c9ea7ba2-be6f-4675-86d1-8b77fb712a14)

**Comment by Kevadroz** [comment]
fixed in https://github.com/NewWind-Modpacks/NWTweaks-WasteOfWorld/commit/bf53a1c1b96ac6b188dfa4e979c2fdeebb0e45df
