### ISSUE TITLE
Manifest formatter fails

### ISSUE THREAD

**Issue by Kevadroz** [NewWind-Modpacks/Waste-of-World#9]
[LOG](https://github.com/NewWind-Modpacks/Waste-of-World/actions/runs/6991338918/job/19021810349)

**Comment by FOREVEREALIZE** [comment]
For now it is expected that, if the `manifest.json` doesn't change, the formatter fails.
I'm working on a fix though.

Technical explanation is that, since nothing changed, there is nothing to commit, hence the command fails.
